server:
  port: 8081

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:h2:mem:accountdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
